application: liamnewmarch-blog
version: live
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /.well-known/acme-challenge/(.+)
  static_files: .challenge/\1
  upload: .challenge/(.+)
  mime_type: text/plain
  secure: optional

- url: /assets/(.+\.(map|md|scss))
  static_files: static/\1
  upload: static/(.+\.(map|md|scss))
  mime_type: text/plain
  secure: always
  application_readable: true

- url: /assets/
  static_dir: static/
  secure: always
  application_readable: true

- url: /.*
  static_dir: build
  secure: always

skip_files:
  # folders
- ^\.git
- ^\.sass-cache
- ^content
- ^grunt
- ^node_modules
- ^static
- ^views
  # files
- .*\.pyc
- \.gitignore
- ^Gruntfile.js
- ^package.json
- ^podspec.yaml
- ^README.md
