application: liamnewmarch-blog
version: live
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup|internalupload).*
  script: blog.wsgi.application
  login: admin
  secure: always

- url: /static/admin/
  static_dir: sitepackages/django/contrib/admin/static/admin/
  secure: always

- url: /admin.*
  script: blog.wsgi.application
  secure: always
  login: admin

- url: /assets/(.+\.(map|md|scss))
  static_files: static/\1
  upload: static/(.+\.(map|md|scss))
  mime_type: text/plain
  secure: always
  application_readable: true

- url: /assets/
  static_dir: static/
  secure: always
  application_readable: true

- url: /.*
  script: blog.wsgi.application
  secure: always

skip_files:
  # folders
- ^\.git.*
- ^grunt.*
- ^node_modules.*
- ^sitepackages/google_appengine.*
  # files
- (.*)\.pyc
- ^CNAME
- ^Gruntfile.js
- ^install_deps
- ^manage.py
- ^package.json
- ^README.md
- ^requirements.txt
- \.storage.*
